version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: QUIZ
      MYSQL_USER: root
      MYSQL_PASSWORD: root1234
      MYSQL_ROOT_PASSWORD: root1234
    volumes:
      - mysql_data:/var/lib/mysql

  server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    environment:
      MYSQL_DATABASE: QUIZ
      MYSQL_USER: root
      MYSQL_PASSWORD: root1234
      MYSQL_HOST: mysql
    ports:
      - "8383:8383"
    volumes:
      - ./app:/app

volumes:
  mysql_data:
